server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://sql12.freemysqlhosting.net:3306/sql12653917?allowPublicKeyRetrieval=true&useSSL=true&sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbc CompliantTruncation=false
    username: sql12653917
    password: gPKBFpEnqb

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    #  Email config
  mail:
    host: smtp.gmail.com
    port: 587
    username: my.cosmetic.store2023@gmail.com
    password: tlkuhzkbrhamtgtk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
